name: Deploy NextJS Food Plaza

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install & Build
        run: |
          npm install
          # Wajib generate prisma client sebelum build
          npx prisma generate 
          npm run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Copy to Server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Kita ambil standalone, static, dan public secara utuh
          source: ".next/standalone,.next/static,public,prisma,package.json"
          target: "/var/www/food-plaza"
          # strip_components diatur ke 0 agar struktur folder terjaga
          strip_components: 0

      - name: Start/Restart PM2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/food-plaza
            
            # 1. Rapikan struktur Standalone
            mkdir -p .next/standalone/.next/static
            cp -r .next/static/. .next/standalone/.next/static/
            cp -r public/. .next/standalone/public/
            
            # 2. Jalankan Migrasi Prisma
            export DATABASE_URL="${{ secrets.DATABASE_URL }}"
            npx prisma migrate deploy

            # 3. Jalankan Server dengan Environment DuckDNS
            cd .next/standalone
            pm2 delete food-plaza || true
            
            # TAMBAHKAN NEXTAUTH_URL DI SINI
            PORT=3000 \
            DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            NEXTAUTH_URL="http://foodplaza.duckdns.org:3000" \
            AUTH_SECRET="${{ secrets.AUTH_SECRET }}" \
            GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
            GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
            AUTH_TRUST_HOST=true \
            pm2 start server.js --name "food-plaza"
            
            pm2 save