name: Deploy NextJS Food Plaza

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install & Build
        run: |
          npm install
          # Wajib generate prisma client sebelum build
          npx prisma generate 
          npm run build
        env:
          # Prisma butuh ini saat build untuk validasi schema
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Copy to Server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Tambahkan prisma/* agar bisa migrate di server
          source: ".next/standalone/*,.next/static/*,public/*,prisma/*"
          target: "/var/www/food-plaza"
          strip_components: 1

      - name: Start/Restart PM2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/food-plaza
            
            # Setup folder standalone
            mkdir -p .next/standalone/.next
            cp -r .next/static .next/standalone/.next/
            cp -r public .next/standalone/
            
            # Jalankan migrasi database di server
            npx prisma migrate deploy

            # Restart PM2
            pm2 delete food-plaza || true
            PORT=3000 pm2 start .next/standalone/server.js --name "food-plaza"
            pm2 save